language: rust
cache: cargo
matrix:
  include:
  - rust: stable
    env:
    - DANCE=OVER_ALL_THE_CRATES
    - RUST_BACKTRACE=full
    script: cargo test --all
  - rust: stable
    env:
    - DANCE=DOCS_WALTZ
    - WALTZ_VERSION=0.1.3
    before_script: |
        if [[ -z "$(which waltz)" ]] || [[ -z "$(waltz --version | grep $WALTZ_VERSION)" ]]; then \
        cargo install waltz_cli --vers $WALTZ_VERSION --force; \
        else echo "waltz already installed"; \
        fi
    script: docs/_test.sh
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - staging
    - trying
